import { ReactElement } from 'react'
import { useSelector } from 'react-redux'
import Head from 'next/head'

// base components
import { MainLayout, ViewLayout, MainStateLayout, Typography } from '../components'

// state
import { RootState } from '../store/store'

const HomePage = (): ReactElement => {
    const { mode } = useSelector((store: RootState) => store.theme)
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Typography variant="h1" color={mode === 'dark' ? 'light' : 'dark'}>
                HomePage
            </Typography>
        </>
    )
}

export default HomePage

HomePage.getLayout = function getLayout(page: ReactElement) {
    return (
        <MainStateLayout title="Open Jira" description="Open Jira description">
            <MainLayout>
                <ViewLayout>{page}</ViewLayout>
            </MainLayout>
        </MainStateLayout>
    )
}
