import { ReactElement } from 'react';
import Head from 'next/head';

// base components
import { MainLayout } from '../components';

const HomePage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>HomePage</h1>
		</>
	);
};

export default HomePage;

HomePage.getLayout = function getLayout(page: ReactElement) {
	return (
		<MainLayout
			title='Example'
			description='Example description'
			contentDescription='Example description'
		>
			{page}
		</MainLayout>
	);
};
